from bnn.model.cifar.cifar import CIFARClassifier
from bnn.model.cifar.shifted_cifar import ShiftedCIFARClassifier
from bnn.model.cifar.bayesian_cifar import BayesianCIFARClassifier
from bnn.model.cifar.shifted_bayesian_cifar import ShiftedBayesianCIFARClassifier
from bnn.model.cifar.mixture_cifar import MixtureCIFARClassifier
from bnn.model.mnist.mnist import MNISTClassifier
from bnn.model.mnist.shifted_mnist import ShiftedMNISTClassifier
from bnn.model.mnist.bayesian_mnist import BayesianMNISTClassifier
from bnn.model.mnist.shifted_bayesian_mnist import ShiftedBayesianMNISTClassifier
from bnn.model.mnist.mixture_mnist import MixtureMNISTClassifier
